import type { Course } from "./types";

export const menuData: Course[] = [
  {
    id: 1,
    courseNumber: "Primer Tiempo",
    title: "PRIMER HOGAR",
    description: "Focaccia de arándanos y jamón serrano con harina de Tenebrio molitor, acompañada de mantequilla saborizada y queso crema.",
    storytelling: "Este primer plato representa el inicio de todo. Nuestra amistad comenzó incluso antes de ingresar oficialmente a la universidad, durante el curso de nivelación, cuando el contacto era únicamente virtual. Aun así, se generó una conexión inmediata. El primer día presencial, sin planearlo demasiado, nos sentamos juntos y desde ese momento hemos compartido la mayoría de los procesos académicos y personales. Como el pan, esta amistad ha sido base y sostén. Ha estado presente en proyectos, discusiones, desacuerdos y reconciliaciones, pero nunca se ha roto. Los arándanos simbolizan los momentos de alegría y risa constante; el jamón serrano representa el paso del tiempo y la madurez que se va construyendo con los años. Primer Hogar es ese espacio seguro donde todo comenzó y al que siempre se puede regresar.",
    characteristics: [
      "Preparación panaria contemporánea y sostenible.",
      "Combinación de sabores dulces y salados.",
      "Alto valor proteico gracias a la harina de Tenebrio.",
    ],
    steps: [
      "Preparación de la masa de focaccia con harina de trigo y Tenebrio molitor.",
      "Hidratación y amasado.",
      "Fermentación controlada.",
      "Incorporación de arándanos y jamón.",
      "Horneado.",
      "Elaboración de mantequilla saborizada.",
      "Montaje final.",
    ],
    techniques: "Amasado, fermentación, horneado, cremado, montaje.",
    sensoryProfile: "Notas tostadas, frutales y salinas; textura esponjosa y miga densa.",
    ods: [
      "ODS 2: Hambre cero, promoviendo fuentes de proteína alternativas y sostenibles.",
      "ODS 12: Producción y consumo responsables, mediante el uso de ingredientes de bajo impacto ambiental.",
    ],
    academicSustenance: "La entomofagia, o consumo de insectos, es una práctica ancestral que actualmente se investiga como solución a la crisis alimentaria global, ofreciendo una fuente de proteína de alta calidad con una baja huella ecológica (van Huis et al., 2013).",
  },
  {
    id: 2,
    courseNumber: "Segundo Tiempo",
    title: "VÍNCULO DULCE",
    description: "Sorbet de mango con espuma de uvilla, gel de mora y crumble de cacao con harina de Tenebrio molitor.",
    storytelling: "Este plato representa a Norah y la forma delicada en la que se fue construyendo nuestra amistad con ella. Al inicio era una persona reservada, tímida y silenciosa, que observaba más de lo que hablaba. Con el tiempo, fue encontrando confianza y seguridad, tanto dentro como fuera del grupo. El sorbet, fresco y equilibrado, refleja esa suavidad en su forma de sentir. Las capas del plato simbolizan el proceso gradual de apertura emocional y la profundidad de un afecto que no siempre se expresa con palabras. Vínculo Dulce representa una amistad sincera, justa y constante, que se mantiene incluso en los momentos de distancia.",
    characteristics: [
      "Preparación fría y refrescante.",
      "Contraste de texturas y acidez.",
      "Crumble proteico y sostenible.",
    ],
    steps: [
      "Base de sorbet de mango natural.",
      "Congelación y turbinar.",
      "Espuma de uvilla.",
      "Gelificación de mora.",
      "Elaboración del crumble con harina de Tenebrio.",
      "Emplatado.",
    ],
    techniques: "Sorbetización, gelificación, espumado, horneado.",
    sensoryProfile: "Ácido-dulce, fresco, crujiente, con un fondo a nuez.",
    ods: [
      "ODS 3: Salud y bienestar, por el uso de preparaciones ligeras y basadas en fruta.",
      "ODS 13: Acción por el clima, al priorizar ingredientes de bajo impacto hídrico y de carbono.",
    ],
    academicSustenance: "El uso de harinas de insectos en la panadería y repostería no solo mejora el perfil nutricional del producto final, sino que también reduce la dependencia de harinas tradicionales con mayor impacto ambiental (Duda et al., 2019).",
  },
  {
    id: 3,
    courseNumber: "Tercer Tiempo",
    title: "SUSURRO SUAVE",
    description: "Gyoza de cerdo y verduras con masa enriquecida con harina de Tenebrio molitor, servidas con salsa de soja y ajonjolí.",
    storytelling: "Alan es la última incorporación al grupo. Nos conocimos mejor cocinando juntos en la cocina, y aunque al inicio el proceso de integración fue lento, con el tiempo empezó a encajar de manera natural. Su personalidad es alegre, genuina y fuerte. La gyoza, cerrada por fuera y llena de sabor en su interior, simboliza esa forma de ser que se descubre poco a poco. Susurro Suave representa una amistad que no irrumpe, sino que se construye con paciencia, aceptación y convivencia.",
    characteristics: [
      "Cocina asiática sostenible.",
      "Masa con mayor aporte de nutrientes.",
      "Técnica de cocción mixta (sellado y vapor).",
    ],
    steps: [
      "Elaboración de masa para gyoza con harina de trigo y Tenebrio.",
      "Preparación del relleno de cerdo y verduras.",
      "Plegado artesanal de las piezas.",
      "Sellado a la plancha y cocción al vapor.",
      "Preparación de la salsa.",
      "Servicio inmediato.",
    ],
    techniques: "Amasado, plegado, vaporización, reducción.",
    sensoryProfile: "Umami intenso, jugoso y crujiente en la base, con un matiz terroso.",
    ods: [
      "ODS 11: Ciudades y comunidades sostenibles, promoviendo la diversidad cultural y la innovación alimentaria.",
      "ODS 15: Vida de ecosistemas terrestres, al reducir la presión sobre la agricultura convencional.",
    ],
    academicSustenance: "La integración de ingredientes sostenibles en recetas tradicionales es una forma de preservar la cultura gastronómica mientras se adapta a los desafíos ambientales del siglo XXI (UNESCO, 2020).",
  },
  {
    id: 4,
    courseNumber: "Cuarto Tiempo",
    title: "PULSO SERENO",
    description: "Ravioles caseros de pollo con masa fresca de harina de Tenebrio molitor, bañados en una delicada salsa aurora y aceite de cebollín.",
    storytelling: "Este plato me representa a mí dentro del grupo. Soy una persona extrovertida y alegre, pero también reflexiva, con un carácter firme y una tendencia natural a organizar, escuchar y aconsejar. En muchas ocasiones, mis amigos acuden a mí en busca de apoyo o claridad. Los ravioles reflejan estructura y orden; el higo aporta dulzura y profundidad. Pulso Sereno simboliza esa energía constante que mantiene el equilibrio del grupo, una presencia que acompaña y sostiene sin imponerse.",
    characteristics: [
      "Pasta fresca artesanal y proteica.",
      "Salsa clásica de la cocina francesa.",
      "Plato reconfortante con un giro innovador.",
    ],
    steps: [
      "Elaboración de la masa fresca con harina de trigo y Tenebrio.",
      "Reposo y laminado.",
      "Preparación del relleno de pollo.",
      "Cocción de los ravioles.",
      "Elaboración de la salsa aurora.",
      "Emulsión con aceite de cebollín y montaje.",
    ],
    techniques: "Pastificación, laminado, hervor, emulsión.",
    sensoryProfile: "Suave, lácteo, herbal, con un sutil sabor a frutos secos en la pasta.",
    ods: [
      "ODS 4: Educación de calidad, fomentando el aprendizaje colaborativo y la innovación.",
      "ODS 9: Industria, innovación e infraestructura, aplicando nuevas tecnologías alimentarias.",
    ],
    academicSustenance: "La adición de harinas alternativas a la pasta fresca puede mejorar su valor nutricional, especialmente en términos de proteínas y minerales, sin alterar significativamente sus propiedades reológicas (Bonomi et al., 2016).",
  },
  {
    id: 5,
    courseNumber: "Quinto Tiempo",
    title: "VERDE NOBLE",
    description: "Croqueta de yuca rellena de queso, empanizada en panko y harina de Tenebrio molitor, acompañada de salsa de aguacate y hebras de pollo.",
    storytelling: "Esta amistad nació entre proyectos académicos y situaciones espontáneas, como aquel trabajo de inglés que terminó con risas, tierra regada y pequeños cactus en macetas. Andrés es una persona tímida, afectuosa y genuina, que quiere de forma sincera. Los ingredientes del plato evocan la tierra, lo simple y lo honesto. Verde Noble representa un cariño limpio, resistente y auténtico, que crece con el tiempo.",
    characteristics: [
      "Fritura profunda y controlada.",
      "Inspiración en la cocina latinoamericana.",
      "Textura extra crujiente y mayor valor nutritivo.",
    ],
    steps: [
      "Cocción y triturado de la yuca.",
      "Formado de la masa con el relleno de queso.",
      "Empanizado con panko y harina de Tenebrio.",
      "Fritura hasta obtener un dorado perfecto.",
      "Preparación de la salsa de aguacate.",
      "Montaje con hebras de pollo.",
    ],
    techniques: "Triturado, empanizado, fritura, emulsión.",
    sensoryProfile: "Extra crujiente, cremoso, con notas tostadas y frescas.",
    ods: [
      "ODS 1: Fin de la pobreza, al revalorizar ingredientes locales y accesibles.",
      "ODS 8: Trabajo decente y crecimiento económico, fomentando la innovación en la cadena de valor alimentaria.",
    ],
    academicSustenance: "El uso de insectos en la alimentación no solo es sostenible, sino que también puede mejorar la seguridad alimentaria en comunidades vulnerables, al ser una fuente de ingresos y nutrientes de fácil acceso (FAO, 2013).",
  },
  {
    id: 6,
    courseNumber: "Sexto Tiempo",
    title: "ENCUENTRO CÁLIDO",
    description: "Tarta Fraisier con bizcocho genovés de harina de Tenebrio molitor, crema muselina a la vainilla, fresas frescas y gel de maracuyá.",
    storytelling: "Vanessa no formó parte del grupo desde el inicio, pero cuando llegó, encajó de manera natural. Su integración fue rápida, y con poco tiempo se construyó una cercanía real. Este postre, compuesto por capas, simboliza las relaciones que se forman poco a poco. Encuentro Cálido representa el momento en el que alguien deja de estar solo y encuentra un espacio compartido.",
    characteristics: [
      "Pastelería clásica francesa reinventada.",
      "Bizcocho con un perfil nutricional mejorado.",
      "Equilibrio entre dulzor, acidez y notas a nuez.",
    ],
    steps: [
      "Elaboración del bizcocho genovés con harina de Tenebrio.",
      "Preparación de la crema muselina.",
      "Gelificación del maracuyá.",
      "Montaje de la tarta con fresas frescas.",
      "Refrigeración y acabado final.",
    ],
    techniques: "Batido, emulsión, gelificación, montaje en capas.",
    sensoryProfile: "Dulce, ácido, cremoso y fresco, con un bizcocho de sabor profundo.",
    ods: [
      "ODS 12: Producción y consumo responsables, al innovar con ingredientes sostenibles en la alta pastelería.",
      "ODS 13: Acción por el clima, reduciendo la huella de carbono de los postres.",
    ],
    academicSustenance: "La innovación en pastelería mediante el uso de ingredientes no convencionales como la harina de insectos permite crear productos con perfiles de sabor novedosos y un menor impacto ambiental, respondiendo a las demandas del consumidor consciente (Orkusz et al., 2020).",
  },
  {
    id: 7,
    courseNumber: "Séptimo Tiempo",
    title: "CONTRASTE DULCE",
    description: "Cheesecake invertido con base de galleta de Tenebrio molitor, compota de frutos rojos y cobertura de chocolate rosado.",
    storytelling: "Este plato representa a Eric. Su humor distinto y su forma particular de ver el mundo encajaron con lo poco convencional de nuestro grupo, y terminaron enriqueciendo la dinámica del grupo. El cheesecake invertido simboliza esa ruptura de lo tradicional. Contraste Dulce celebra la diferencia como un valor que fortalece la amistad.",
    characteristics: [
      "Postre de vanguardia y sostenible.",
      "Presentación visual innovadora.",
      "Base de galleta crujiente y nutritiva.",
    ],
    steps: [
      "Elaboración de la base de galleta con harina de Tenebrio.",
      "Preparación de la mezcla de cheesecake.",
      "Gelificación y congelación en molde invertido.",
      "Preparación de la compota de frutos rojos.",
      "Desmolde y decoración con chocolate.",
    ],
    techniques: "Cremado, horneado, gelificación, inversión.",
    sensoryProfile: "Cremoso, dulce equilibrado, con acidez frutal y una base de sabor a cereal tostado.",
    ods: [
      "ODS 9: Industria, innovación e infraestructura, por la aplicación de técnicas modernas y materiales sostenibles.",
      "ODS 17: Alianzas para lograr los objetivos, al conectar gastronomía, ciencia y sostenibilidad.",
    ],
    academicSustenance: "La cocina de vanguardia busca constantemente desafiar los límites de la gastronomía, no solo en la técnica y presentación, sino también en el origen y la sostenibilidad de sus ingredientes, abriendo camino a una nueva era culinaria (Aduriz, 2012).",
  },
  {
    id: 8,
    courseNumber: "Octavo Tiempo",
    title: "BRUMA ROSA",
    description: "Licor cremoso artesanal de pétalos de rosa, acompañado de una rodaja de naranja deshidratada para perfumar.",
    storytelling: "Este último plato representa a Thalía y cierra el menú. Su amistad se construyó con el tiempo, de forma silenciosa y constante. Es una presencia suave, que acompaña y permanece. El licor, delicado y persistente, simboliza los recuerdos que se quedan. Bruma Rosa representa la memoria compartida, el cierre emocional del recorrido y la permanencia de la amistad.",
    characteristics: [
      "Bebida digestiva y aromática.",
      "Cierre elegante y sensorial del menú.",
      "Elaboración por maceración.",
    ],
    steps: [
      "Maceración de pétalos de rosa en alcohol.",
      "Filtrado y clarificación.",
      "Emulsión con una base láctea.",
      "Deshidratación de rodajas de naranja.",
      "Servicio frío.",
    ],
    techniques: "Maceración, emulsión, deshidratación.",
    sensoryProfile: "Floral, dulce, cremoso y persistente.",
    ods: [
      "ODS 17: Alianzas para lograr los objetivos, simbolizando la red de contactos que se lleva al mundo profesional.",
      "ODS 12: Consumo responsable, promoviendo la elaboración artesanal.",
    ],
    academicSustenance: "La elaboración de licores artesanales mediante maceración es una práctica histórica que permite extraer compuestos aromáticos y medicinales de plantas, siendo una forma de conservación y valorización de recursos botánicos (Jackson, 2008).",
  },
];
