import type { Course } from "./types";

export const menuData: Course[] = [
  {
    id: 1,
    courseNumber: "Primer Tiempo",
    title: "PRIMER HOGAR",
    description: "Focaccia de arándanos y jamón serrano elaborada con sustitución del 25 % de harina de trigo por harina de Tenebrio molitor, acompañada de mantequilla saborizada y queso crema.",
    storytelling: "Este primer plato representa el inicio de todo. Nuestra amistad comenzó incluso antes de ingresar oficialmente a la universidad, durante el curso de nivelación, cuando el contacto era únicamente virtual. Aun así, se generó una conexión inmediata. El primer día presencial, sin planearlo demasiado, nos sentamos juntos y desde ese momento hemos compartido la mayoría de los procesos académicos y personales. Como el pan, esta amistad ha sido base y sostén. Ha estado presente en proyectos, discusiones, desacuerdos y reconciliaciones, pero nunca se ha roto. Los arándanos simbolizan los momentos de alegría y risa constante; el jamón serrano representa el paso del tiempo y la madurez que se va construyendo con los años. Primer Hogar es ese espacio seguro donde todo comenzó y al que siempre se puede regresar.",
    universityStorytelling: "Este primer tiempo simboliza el inicio de la vida universitaria, el momento en que el estudiante abandona lo conocido para adentrarse en un nuevo entorno académico. El azahar, flor asociada al comienzo de los ciclos, representa el primer contacto con el conocimiento formal, mientras que la focaccia remite a lo familiar. La harina de Tenebrio molitor introduce la innovación y el pensamiento crítico, elementos fundamentales del proceso formativo universitario.",
    characteristics: [
      "Preparación panaria contemporánea.",
      "Integración de ingredientes alternativos.",
      "Adaptable a menús sostenibles.",
    ],
    steps: [
      "Mezcla de harinas (75 % trigo, 25 % Tenebrio molitor).",
      "Hidratación y amasado.",
      "Fermentación controlada.",
      "Incorporación de arándanos y jamón.",
      "Horneado.",
      "Elaboración de mantequilla saborizada.",
      "Montaje final.",
    ],
    techniques: "Amasado directo, fermentación, horneado, cremado, montaje.",
    sensoryProfile: "Notas tostadas, frutales y salinas; textura esponjosa y miga densa.",
    ods: [
      "ODS 4: Educación de calidad, al promover la innovación y el pensamiento crítico.",
      "ODS 12: Producción y consumo responsables, mediante el uso de ingredientes alternativos sostenibles.",
    ],
    academicSustenance: "El uso de insectos comestibles en productos panarios ha demostrado ser viable tanto sensorial como ambientalmente, favoreciendo modelos alimentarios más sostenibles (Van Huis et al., 2013; FAO, 2013).",
  },
  {
    id: 2,
    courseNumber: "Segundo Tiempo",
    title: "VÍNCULO DULCE",
    description: "Sorbet de mango con espuma de uvilla, gel de mora y crumble de cacao elaborado con 25 % de harina de Tenebrio molitor.",
    storytelling: "Este plato representa a Norah y la forma delicada en la que se fue construyendo nuestra amistad con ella. Al inicio era una persona reservada, tímida y silenciosa, que observaba más de lo que hablaba. Con el tiempo, fue encontrando confianza y seguridad, tanto dentro como fuera del grupo. El sorbet, fresco y equilibrado, refleja esa suavidad en su forma de sentir. Las capas del plato simbolizan el proceso gradual de apertura emocional y la profundidad de un afecto que no siempre se expresa con palabras. Vínculo Dulce representa una amistad sincera, justa y constante, que se mantiene incluso en los momentos de distancia.",
    universityStorytelling: "",
    characteristics: [
      "Preparación fría.",
      "Contraste de texturas.",
      "Enfoque sensorial.",
    ],
    steps: [
      "Base de sorbet.",
      "Congelación y turbinar.",
      "Espuma de uvilla.",
      "Gelificación de mora.",
      "Crumble con harina de insecto.",
      "Emplatado.",
    ],
    techniques: "Sorbetización, gelificación, espumado, horneado.",
    sensoryProfile: "Ácido-dulce, fresco, crujiente.",
    ods: [
      "ODS 3: Salud y bienestar, por el uso de preparaciones ligeras y balanceadas.",
      "ODS 13: Acción por el clima, al priorizar técnicas de bajo impacto ambiental.",
    ],
    academicSustenance: "Diversos estudios indican que las preparaciones frías y el uso de ingredientes de bajo impacto reducen la huella ambiental de los alimentos (Oonincx & de Boer, 2012).",
  },
  {
    id: 3,
    courseNumber: "Tercer Tiempo",
    title: "SUSURRO SUAVE",
    description: "Gyoza de cerdo y verduras con masa al 25 % de harina de Tenebrio molitor, salsa de soja y ajonjolí.",
    storytelling: "Alan es la última incorporación al grupo. Nos conocimos mejor cocinando juntos en la cocina, y aunque al inicio el proceso de integración fue lento, con el tiempo empezó a encajar de manera natural. Su personalidad es alegre, genuina y fuerte. La gyoza, cerrada por fuera y llena de sabor en su interior, simboliza esa forma de ser que se descubre poco a poco. Susurro suave representa una amistad que no irrumpe, sino que se construye con paciencia, aceptación y convivencia.",
    universityStorytelling: "",
    characteristics: [
      "Cocina asiática reinterpretada.",
      "Enfoque en umami.",
      "Cocción mixta.",
    ],
    steps: [
      "Masa con harina mixta.",
      "Relleno.",
      "Plegado.",
      "Sellado y vapor.",
      "Salsa.",
      "Servicio.",
    ],
    techniques: "Amasado, plegado, vaporización, reducción.",
    sensoryProfile: "Umami intenso, jugoso y crujiente.",
    ods: [
      "ODS 2: Hambre cero, al promover fuentes alternativas de proteína.",
      "ODS 12: Producción responsable, por la integración de insectos como recurso eficiente.",
    ],
    academicSustenance: "La harina de Tenebrio molitor ha sido ampliamente reconocida como una alternativa sostenible a proteínas tradicionales, con menor huella hídrica y ambiental (Rumpold & Schlüter, 2013).",
  },
  {
    id: 4,
    courseNumber: "Cuarto Tiempo",
    title: "PULSO SERENO",
    description: "Ravioles de pollo con masa fresca al 25 % de harina de Tenebrio molitor, salsa aurora y aceite de cebollín.",
    storytelling: "Patty sin saberlo se convirtió en mi mejor amiga, talvez podría decirse que estábamos destinados a conocernos, pero el destino esperó hasta llegar a la u para vincularnos, sin saber lo parecido que seríamos ella es extrovertida y alegre, pero también reflexiva, con un carácter firme y una tendencia natural a organizar, escuchar y aconsejar. En muchas ocasiones, nuestros amigos acuden a ella en busca de apoyo o claridad. Los ravioles reflejan estructura y orden; el higo aporta dulzura y profundidad. Pulso Sereno simboliza esa energía constante que mantiene el equilibrio del grupo, una presencia que acompaña y sostiene sin imponerse.",
    universityStorytelling: "",
    characteristics: [
      "Pasta fresca artesanal.",
      "Servicio inmediato.",
      "Técnica clásica reinterpretada.",
    ],
    steps: [
      "Masa fresca.",
      "Reposo y laminado.",
      "Relleno.",
      "Cocción.",
      "Salsa aurora.",
      "Emulsión y montaje.",
    ],
    techniques: "Pastificación, laminado, hervor, emulsión.",
    sensoryProfile: "Suave, lácteo, herbal.",
    ods: [
      "ODS 4: Educación de calidad",
      "ODS 11: Comunidades sostenibles, al fomentar prácticas colaborativas y culturales.",
    ],
    academicSustenance: "La gastronomía es reconocida como una herramienta de cohesión social y transmisión cultural (Contreras & Gracia, 2005).",
  },
  {
    id: 5,
    courseNumber: "Quinto Tiempo",
    title: "VERDE NOBLE",
    description: "Croqueta de yuca con masa al 25 % de harina de Tenebrio molitor, rellena de queso, salsa de aguacate y pollo.",
    storytelling: "Esta amistad nació entre proyectos académicos y situaciones espontáneas, como aquel trabajo de inglés que terminó con risas, tierra regada y pequeños cactus en macetas. Andrés es una persona tímida, afectuosa y genuina, que quiere de forma sincera. Los ingredientes del plato evocan la tierra, lo simple y lo honesto. Verde Noble representa un cariño limpio, resistente y auténtico, que crece con el tiempo.",
    universityStorytelling: "",
    characteristics: [
      "Fritura controlada.",
      "Producto de contraste.",
      "Inspiración ancestral.",
    ],
    steps: [
      "Cocción y triturado de yuca.",
      "Mezcla con harina de insecto.",
      "Relleno.",
      "Empanizado.",
      "Fritura.",
      "Salsas.",
    ],
    techniques: "Triturado, empanizado, fritura, emulsión.",
    sensoryProfile: "Crujiente, cremoso, tostado.",
    ods: [
      "ODS 9: Industria, innovación e infraestructura",
      "ODS 12: Consumo responsable",
    ],
    academicSustenance: "La integración de ingredientes tradicionales y alternativos fortalece la sostenibilidad alimentaria y cultural (FAO, 2013).",
  },
  {
    id: 6,
    courseNumber: "Sexto Tiempo",
    title: "ENCUENTRO CÁLIDO",
    description: "Tarta Fraisier con bizcocho al 25 % de harina de Tenebrio molitor, crema pastelera y gel de maracuyá.",
    storytelling: "Vanessa no formó parte del grupo desde el inicio, pero cuando llegó, encajó de manera natural. Su integración fue rápida, y con poco tiempo se construyó una cercanía real. Siempre está cuando se la necesita es generosa, bondadosa y una persona en quien confiar. Este postre, compuesto por capas, simboliza las relaciones que se forman poco a poco. Encuentro Cálido representa el momento en el que alguien deja de estar solo y encuentra un espacio compartido.",
    universityStorytelling: "",
    characteristics: [
      "Pastelería estratificada.",
      "Técnicas de precisión.",
    ],
    steps: [
      "Bizcocho.",
      "Crema pastelera.",
      "Gelificación.",
      "Montaje.",
    ],
    techniques: "Batido, emulsión, gelificación.",
    sensoryProfile: "Dulce-ácido, suave.",
    ods: [
      "ODS 8: Trabajo decente y crecimiento económico",
      "ODS 12: Producción responsable",
    ],
    academicSustenance: "La reformulación de productos de pastelería con ingredientes alternativos permite innovar sin perder aceptación sensorial (Caparros Megido et al., 2014).",
  },
  {
    id: 7,
    courseNumber: "Séptimo Tiempo",
    title: "CONTRASTE DULCE",
    description: "Cheesecake invertido con base al 25 % de harina de Tenebrio molitor, frutos rojos y chocolate rosado.",
    storytelling: "Este plato representa a Erick. Su humor distinto y su forma particular de ver el mundo encajaron con lo poco convencional de nuestro grupo, y terminaron enriqueciendo la dinámica del grupo. El cheesecake invertido simboliza esa ruptura de lo tradicional. Contraste Dulce celebra la diferencia como un valor que fortalece la amistad.",
    universityStorytelling: "",
    characteristics: [
      "Postre contemporáneo.",
      "Juego visual y sensorial.",
    ],
    steps: [
      "Base horneada.",
      "Mezcla de queso.",
      "Gelificación.",
      "Inversión.",
      "Decoración.",
    ],
    techniques: "Cremado, horneado, inversión.",
    sensoryProfile: "Cremoso, dulce equilibrado.",
    ods: [
      "ODS 4: Educación de calidad",
      "ODS 12: Producción responsable",
    ],
    academicSustenance: "La aceptación sensorial es clave para la incorporación de nuevos ingredientes en la gastronomía contemporánea (Hartmann & Siegrist, 2017).",
  },
  {
    id: 8,
    courseNumber: "Octavo Tiempo",
    title: "BRUMA ROSA",
    description: "Licor cremoso de pétalos de rosa con 25 % de harina de Tenebrio molitor, acompañado de naranja deshidratada.",
    storytelling: "Este último plato representa a Thalía y cierra el menú. Su amistad se construyó con el tiempo, de forma silenciosa y constante. Es una presencia suave, que acompaña y permanece. Ella ha sido una amiga incondicional que nos ha acompañado en momentos alegres y tristes, y siempre ha sido fiel a nosotros, además de ser una persona muy serena ella se ha convertido en una de nuestras mejores amistades que si la necesitamos ella está para ayudarnos. El licor, delicado y persistente, simboliza los recuerdos que se quedan. Bruma Rosa representa la memoria compartida, el cierre emocional del recorrido y la permanencia de la amistad.",
    universityStorytelling: "",
    characteristics: [
      "Preparación líquida.",
      "Cierre aromático del menú.",
    ],
    steps: [
      "Maceración.",
      "Filtrado.",
      "Emulsión.",
      "Deshidratación.",
      "Servicio.",
    ],
    techniques: "Maceración, emulsión, deshidratación.",
    sensoryProfile: "Floral, dulce, persistente.",
    ods: [
      "ODS 17: Alianzas para lograr los objetivos, al promover investigación y transferencia de conocimiento.",
      "ODS 12: Consumo responsable",
    ],
    academicSustenance: "El desarrollo de productos innovadores a partir de insectos contribuye al avance científico y gastronómico sostenible (Van Huis, 2020).",
  },
];
